// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzgizmufxustexkzbup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtemdpem11Znh1c3RleGt6YnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDA3NzEsImV4cCI6MjA1MzM3Njc3MX0.UMgBBxpfG3lsnbTvyxPC2gamOCV0RwxSUi8l9COMFck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);